### ISSUE TITLE
Unable to submit data

### ISSUE THREAD

**Issue by desertjinn** [orionjs/froala-editor#1]
Initiated with :
```javascript
orion.addEntity('anyEntity', {
    body: orion.attribute('froala',{
		label: 'Body',
		optional: true
    })
},  {
	icon: 'bookmark',
	sidebarName: 'Sports',
	pluralName: 'Sports',
	singularName: 'Sport',
});
```

When I try to submit value, throws **undefined type error** :

*Uncaught TypeError: undefined is not a function        (attribute.js:10)*

**attribute.js** : *line no: 10*
```javascript
valueOut: function() {
		return this.find('.editor').editable('getHTML', false, true);
}
```

 I can use the editor but am unable to save any value. I have minimal knowledge in meteor js and this is my first time using froala editor. 

![screenshot from 2015-01-15 16 32 29](https://cloud.githubusercontent.com/assets/9519467/5756327/358f87ca-9cd4-11e4-8d4a-0e8175b3727b.png)

**Comment by nicolaslopezj** [comment]
This is very strange. I tested with the same entity and it worked. Make sure you have the latests versions.

Please try running this code in the browser console and write the result here
```js
$('.editor').editable('getHTML', false, true);
// It should return the content of the editor
```

**Comment by desertjinn** [comment]
![screenshot from 2015-01-15 19 35 46](https://cloud.githubusercontent.com/assets/9519467/5759439/f988f070-9cf3-11e4-8997-ceb0b33cf2c7.png)

And - 

![screenshot from 2015-01-15 19 36 51](https://cloud.githubusercontent.com/assets/9519467/5759354/4715cefe-9cf3-11e4-9dec-5d4bf9c0a7b4.png)

Same result as earlier.

**How I got it to work :**
I created a new  project and added packages in the order : *orionjs:core*, *orionjs:styles*, *orionjs:froala-editor* and *mrt:moment*. The editor works perfectly now and saves everything. :+1:  :+1: . 

I had added the same packages to my project earlier ( I had also added the packages *orionjs:summernote* and *orionjs:admin* to the earlier project ) and I am using the same code to add entities and set the attribute but I have no idea why it does not work in the earlier project.

**Comment by nicolaslopezj** [comment]
Excellent! But I have a doubt. Why mtr:moment changes the result?

**Comment by desertjinn** [comment]
No idea. I had added mrt:moment to the new project I created too as well as
the old one and froala works beautifully without any issues in the new
project. Maybe my dependencies weren't updated ?

**Comment by nicolaslopezj** [comment]
But does it work without mrt:moment?

**Comment by desertjinn** [comment]
I removed moment and updated dependencies but same error. :-1: 

 if it helps my package list is -

**autopublish             1.0.2  Publish the entire database to all clients
insecure                1.0.2  Allow all database writes by default
meteor-platform         1.2.1  Include a standard set of Meteor packages in your app
orionjs:core            0.4.2  Simple and powerful admin panel for meteor
orionjs:file-attribute  0.0.3  File attribute for orion
orionjs:filesystem      0.0.13  Filesystem for orionjs
orionjs:froala-editor   0.1.0  Froala editor for orion
orionjs:styles          0.1.3  Styles for orionjs admin**

**Comment by nicolaslopezj** [comment]
Mm this is strange. But if it worked we are ok

**Comment by desertjinn** [comment]
Yup it worked in the new project :)

**Comment by belmarca** [comment]
That is not a proper fix. There's something going on behind the scenes that makes your code break in my project as well. It works on a fresh project, though. I'll investigate a bit more and try to see what packages interfere, although I've uninstalled them all non-orion ones and it still didn't work...

**Comment by brylie** [comment]
This might be related to the Meteor constraint solver. I.e. Meteor has to choose an optimal version for each package in your project, based dependencies and other packages/their dependencies. This is a complicated process, and can lead to varying results - sometimes with older versions of packages being selected:

* [Meteor Version Solver](https://www.meteor.com/version-solver)
* [Devshop SF - February 2015: Meteor constraint solver](https://www.youtube.com/watch?v=P4wKQympnsg#t=2014)

**Comment by belmarca** [comment]
I think the packages that were interfering were (in bold)

> meteor-platform
> insecure
    orionjs:core
    orionjs:styles
    orionjs:froala-editor
    mquandalle:bower
    fourseven:scss
    momentjs:moment
    **accounts-ui**
    **accounts-password**

which were right after `insecure` before and now do not cause any more problems.
